name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Create config.js
        run: |
          echo "const Config = {" > ./docs/config.js
          echo "  apiKey: '${{ secrets.PUBLIC_API_KEY }}'," >> ./docs/config.js
          echo "};" >> ./docs/config.js
          echo "export default Config;" >> ./docs/config.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs